apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: registry
    chart: registry
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx.conf: |
    events {}
    http {
      client_max_body_size 1G;
      server {
        listen 8080;
        location /v2/ {
          proxy_pass http://localhost:5000/v2/;
        }
      }
    }
