apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  labels:
    app: registry
    chart: registry
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:      
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
